export const ukUniversities = [
  "Aberystwyth University",
  "Anglia Ruskin University",
  "Aston University",
  "Bath Spa University",
  "Birkbeck, University of London",
  "Birmingham City University",
  "Bournemouth University",
  "Brighton University",
  "Bristol University",
  "Brunel University London",
  "Canterbury Christ Church University",
  "Cardiff University",
  "Cardiff Metropolitan University",
  "City, University of London",
  "Coventry University",
  "Cranfield University",
  "De Montfort University",
  "Durham University",
  "East Anglia University",
  "Edinburgh University",
  "Essex University",
  "Exeter University",
  "Glasgow University",
  "Goldsmiths, University of London",
  "Greenwich University",
  "Heriot-Watt University",
  "Hertfordshire University",
  "Huddersfield University",
  "Hull University",
  "Imperial College London",
  "Keele University",
  "Kent University",
  "King's College London",
  "Kingston University",
  "Lancaster University",
  "Leeds University",
  "Leeds Beckett University",
  "Leicester University",
  "Lincoln University",
  "Liverpool University",
  "Liverpool Hope University",
  "Liverpool John Moores University",
  "London School of Economics",
  "London Metropolitan University",
  "London South Bank University",
  "Loughborough University",
  "Manchester University",
  "Manchester Metropolitan University",
  "Middlesex University",
  "Newcastle University",
  "Northumbria University",
  "Norwich University of the Arts",
  "Nottingham University",
  "Nottingham Trent University",
  "Open University",
  "Oxford University",
  "Oxford Brookes University",
  "Plymouth University",
  "Portsmouth University",
  "Queen Mary University of London",
  "Queen's University Belfast",
  "Reading University",
  "Robert Gordon University",
  "Royal Holloway, University of London",
  "Sheffield University",
  "Sheffield Hallam University",
  "Southampton University",
  "Southampton Solent University",
  "Staffordshire University",
  "Stirling University",
  "Strathclyde University",
  "Sunderland University",
  "Surrey University",
  "Sussex University",
  "Swansea University",
  "Teesside University",
  "Ulster University",
  "University College London",
  "University of the West of England",
  "University of the West of Scotland",
  "Warwick University",
  "Westminster University",
  "Winchester University",
  "Wolverhampton University",
  "York University",
  "York St John University"
] as const;

export type UKUniversity = typeof ukUniversities[number];